### ISSUE TITLE
[Feature] Support of UltimakerFormatPackage

### ISSUE THREAD

**Issue by OllisGit** [tjjfvi/OctoPrint-SlicerSettingsParser#7]
Hi @tjjfvi !
First: Thx, for your work!!!!

**Is your feature request related to a problem? Please describe.**
I was playing around with [UltimakerFormatPackage-Plugin](https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage), because I want to store as much information as possible in my [PrintJobHistory-Plugin](https://community.octoprint.org/t/wip-new-print-history-plugin/1633/23). For UFP I want to store the generated Thumbnail.
And now I want to store the slicer settings, parsed by your plugin. 

But unfortunately the parser only reads the file during upload and in that case the file is zipped (.ufp extension) and later extracted.
```
2019-11-15 17:16:14,059 - octoprint.plugin - ERROR - Error while calling plugin SlicerSettingsParser
Traceback (most recent call last):
  File "/Users/o0632/0_Projekte/3DDruck/OctoPrint/octoprint_latest/src/octoprint/plugin/__init__.py", line 219, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/Users/o0632/0_Projekte/3DDruck/OctoPrint/octoprint_latest/venv/lib/python2.7/site-packages/octoprint_SlicerSettingsParser/__init__.py", line 52, in on_event
    self._analyze_file(payload["path"])
  File "/Users/o0632/0_Projekte/3DDruck/OctoPrint/octoprint_latest/venv/lib/python2.7/site-packages/octoprint_SlicerSettingsParser/__init__.py", line 74, in _analyze_file
    file = open(self._storage_interface.path_on_disk(path))
IOError: [Errno 2] No such file or directory: u'/Users/o0632/Library/Application Support/OctoPrint/uploads/CFFFP_TaubenWinkle.ufp
```

**Describe the solution you'd like**
Parse the settings "on file select" event instead of "upload" event.

**Comment by tjjfvi** [comment]
Hi @OllisGit! Does UFP fire the `FileAdded` event? If so, I could add that pretty easily, without any logic for "has this file been processed already?".
